import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { createKnowledgeDocument, getKnowledgeDocuments, knowledgeDocumentAction, searchKnowledge } from '../api'
import type { KnowledgeDocument, KnowledgeSearchResult, SimulatedRole } from '../types'

const shortcuts = [
  ['collateral_liquidity', 'Collateral and liquidity'], ['mandate_suitability', 'Mandate and suitability'],
  ['tax_planning', 'Tax and planning'], ['private_markets', 'Commitments and gated liquidity'], ['evidence', 'Evidence and data quality'],
] as const

function Results({ results }: { results: KnowledgeSearchResult[] }) {
  if (!results.length) return <p className="muted">No approved internal reference matches this search. This is not a request to infer a policy answer.</p>
  return <div className="stack">{results.map((result) => <article className="card" key={`${result.citation.document_id}-${result.citation.version}`}><div className="card-head"><h3>{result.citation.title}</h3><span className="pill ghost">v{result.citation.version}</span></div><div className="card-body"><p style={{ marginTop: 0 }}>{result.excerpt}</p><p className="footnote" style={{ marginBottom: 0 }}>Matched {result.matched_fields.join(', ')} · effective {result.citation.effective_date} · sources: {result.citation.source_refs.join(', ')}</p></div></article>)}</div>
}

export function KnowledgeReferencePanel({ role, category, location }: { role: SimulatedRole; category?: string; location: string }) {
  const [selectedCategory, setSelectedCategory] = useState(category ?? '')
  const [results, setResults] = useState<KnowledgeSearchResult[]>([])
  const [open, setOpen] = useState(false)
  const search = (nextCategory = selectedCategory) => void searchKnowledge({ category: nextCategory || undefined, role, location }).then(({ results: next }) => setResults(next))
  useEffect(() => { if (open) search() }, [open, role]) // eslint-disable-line react-hooks/exhaustive-deps
  return <div className="card" style={{ marginTop: 16, background: 'var(--surface)' }}><div className="card-head"><h3>Approved knowledge reference</h3><button className="btn quiet" onClick={() => setOpen((value) => !value)}>{open ? 'Hide reference' : 'Search reference'}</button></div>{open && <div className="card-body"><p className="footnote" style={{ marginTop: 0 }}>Synthetic internal reference only — not client evidence, advice, a tax conclusion, or a recommendation.</p><div className="filters">{shortcuts.map(([key, label]) => <button key={key} className="chip" aria-pressed={selectedCategory === key} onClick={() => { setSelectedCategory(key); search(key) }}>{label}</button>)}</div><Results results={results} /></div>}</div>
}

export function KnowledgeLibrary({ role }: { role: SimulatedRole }) {
  const [documents, setDocuments] = useState<KnowledgeDocument[]>([])
  const [results, setResults] = useState<KnowledgeSearchResult[]>([])
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('')
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [newDraft, setNewDraft] = useState(false)
  const [message, setMessage] = useState<string | null>(null)
  const [form, setForm] = useState({ title: '', category: 'evidence', tags: 'evidence, data_quality', owner: 'Product Operations', effective_date: '2026-08-26', source_refs: 'clarity/docs/METHOD.md', body: '', rationale: '' })
  const refresh = () => void getKnowledgeDocuments(role).then(({ documents }) => { setDocuments(documents); if (!selectedId && documents[0]) setSelectedId(documents[0].id) }).catch((error) => setMessage(String(error)))
  useEffect(refresh, [role]) // eslint-disable-line react-hooks/exhaustive-deps
  const selected = useMemo(() => documents.find((item) => item.id === selectedId), [documents, selectedId])
  const selectedVersion = selected?.version ?? (selected?.versions ? selected.versions[selected.versions.length - 1] : undefined)
  const search = () => void searchKnowledge({ query, category: category || undefined, role, location: 'knowledge_library' }).then(({ results }) => setResults(results)).catch((error) => setMessage(String(error)))
  const draft = async (event: FormEvent) => { event.preventDefault(); try { const payload = { role, ...form, tags: form.tags.split(',').map((item) => item.trim()).filter(Boolean), source_refs: form.source_refs.split(',').map((item) => item.trim()).filter(Boolean) }; const response = selected?.approved_version && !newDraft ? await knowledgeDocumentAction(selected.id, 'revise', payload) : await createKnowledgeDocument(payload); setSelectedId(response.document.id); setNewDraft(false); setMessage('Knowledge draft saved. It remains unsearchable until Compliance/Audit approval.'); refresh() } catch (error) { setMessage(String(error)) } }
  const action = async (name: 'submit' | 'approve' | 'reject') => { if (!selected) return; try { await knowledgeDocumentAction(selected.id, name, { role, rationale: form.rationale }); const labels = { submit: 'submitted', approve: 'approved', reject: 'rejected' }; setMessage(`Document ${labels[name]}.`); refresh() } catch (error) { setMessage(String(error)) } }
  const loadRevision = (document: KnowledgeDocument) => { const version = document.version ?? document.versions?.[document.versions.length - 1]; if (!version) return; setNewDraft(false); setSelectedId(document.id); setForm({ title: document.title, category: document.category, tags: document.tags.join(', '), owner: document.owner, effective_date: version.effective_date, source_refs: version.source_refs.join(', '), body: version.body, rationale: '' }) }
  const startNewDraft = () => { setNewDraft(true); setForm({ title: '', category: 'evidence', tags: 'evidence, data_quality', owner: 'Product Operations', effective_date: '2026-08-26', source_refs: 'clarity/docs/METHOD.md', body: '', rationale: '' }) }
  return <div className="stack"><div className="card"><div className="card-head"><h1>Knowledge</h1><span className="sub">Approved synthetic reference library</span></div><div className="card-body"><p style={{ marginTop: 0 }}>Searches only approved, local prototype guides. Results are citations for RM reference; they never change signals, decisions, scenarios, gates, meeting packages, or client communication.</p><div className="grid2"><input className="input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search approved knowledge" aria-label="Knowledge query" /><select className="select" value={category} onChange={(event) => setCategory(event.target.value)} aria-label="Knowledge category"><option value="">All categories</option>{shortcuts.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div><div className="filters">{shortcuts.map(([key, label]) => <button key={key} className="chip" aria-pressed={category === key} onClick={() => { setCategory(key); void searchKnowledge({ category: key, role, location: 'knowledge_library' }).then(({ results }) => setResults(results)) }}>{label}</button>)}<button className="btn primary" onClick={search}>Search</button></div><Results results={results} /></div></div>
    <div className="card"><div className="card-head"><h2>Document register</h2><span className="sub">All roles read approved versions</span></div><div className="card-body"><table className="postable"><thead><tr><th>Document</th><th>Current version</th><th /></tr></thead><tbody>{documents.map((document) => <tr key={document.id}><td><strong>{document.title}</strong><div className="muted small">{document.category} · {document.tags.join(', ')}</div></td><td>v{document.current_version} · <span className="pill ghost">{document.version?.status ?? 'history'}</span></td><td><button className="btn quiet" onClick={() => loadRevision(document)}>View</button></td></tr>)}</tbody></table></div></div>
    {role === 'operations' && <form className="card" onSubmit={(event) => void draft(event)}><div className="card-head"><h2>{selected?.approved_version && !newDraft ? 'Draft revision' : 'Draft knowledge document'}</h2><span className="sub">Only controlled local methodology/demo references are allowed</span></div><div className="card-body"><button type="button" className="btn quiet" onClick={startNewDraft}>New document</button><div className="grid2"><input className="input" required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="Title" /><input className="input" required value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} placeholder="Category" /><input className="input" required value={form.tags} onChange={(event) => setForm({ ...form, tags: event.target.value })} placeholder="Tags, comma-separated" /><input className="input" required value={form.owner} onChange={(event) => setForm({ ...form, owner: event.target.value })} placeholder="Owner" /><input className="input" required type="date" value={form.effective_date} onChange={(event) => setForm({ ...form, effective_date: event.target.value })} /><input className="input" required value={form.source_refs} onChange={(event) => setForm({ ...form, source_refs: event.target.value })} placeholder="Controlled local source references" /></div><textarea className="rmnote" required value={form.body} onChange={(event) => setForm({ ...form, body: event.target.value })} placeholder="Synthetic approved-reference wording" /><textarea className="rmnote" required value={form.rationale} onChange={(event) => setForm({ ...form, rationale: event.target.value })} placeholder="Why this draft or revision is needed" /><button className="btn primary">Save draft</button>{!newDraft && selectedVersion?.status === 'draft' && <button type="button" className="btn" style={{ marginLeft: 8 }} onClick={() => void action('submit')}>Submit to Compliance/Audit</button>}</div></form>}
    {role === 'compliance_audit' && selectedVersion?.status === 'submitted' && <div className="card"><div className="card-head"><h2>Compliance/Audit review</h2></div><div className="card-body"><textarea className="rmnote" value={form.rationale} onChange={(event) => setForm({ ...form, rationale: event.target.value })} placeholder="Approval or rejection rationale" /><button className="btn primary" onClick={() => void action('approve')}>Approve version</button><button className="btn" style={{ marginLeft: 8 }} onClick={() => void action('reject')}>Reject version</button></div></div>}
    {message && <div className="banner" role="status">{message}</div>}
  </div>
}
